blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detail'),
    url(r'^post/new/$', views.post_new, name='new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='edit'),
]

counter/urls.py
from django.conf.urls import url

from . import views

app_name = 'counter'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

photos/urls.py
from django.conf.urls import url

from . import views

app_name = 'photos'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^hidden-photos/(?P<pk>[0-9]+)$', views.detail, kwargs={'hidden': True}),
    url(r'^upload/$', views.create, name='create'),
    url(r'^new/$', views.photo_new, name='new'),
]

profiles/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'^(?P<username>[\w.@+-]+)/$', views.profile, name="profile"),
]

youstagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^counter/', include('counter.urls', namespace='counter')),
    url(r'^users/', include('profiles.urls')),
    url(r'^$', views.index, name='index'),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

counter/models.py
from django.db import models

# Create your models here.

photos/models.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.db import models


class Photo(models.Model):
    # id = "개별 사진을 구분하는 색인값"
    # image = "원본 사진 파일"
    # filtered_image = "필터 적용된 사진 파일"
    # content = "사진에 대한 설명문"
    # created_at = "생성일시"

    image = models.ImageField(upload_to='%Y/%m/%d/original')
    # filtered_image = models.ImageField(upload_to='%Y/%m/%d/filtered')
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.image.name

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        url = reverse_lazy('detail', kwargs={'pk': self.pk})
        return url

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

photos/forms.py
from __future__ import unicode_literals

from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'content', )
        # exclude = ('filtered_image', )

blog/views.py
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .forms import PostForm
from .models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

counter/views.py
from django.shortcuts import render


def index(request):
    ctx = {}
    return render(request, 'counter/index.html', ctx)

photos/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .forms import PhotoForm
from .models import Photo


def photo_new(request):
    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('detail', pk=f.id)
        return HttpResponse("Hell world")
    else:
        form = PhotoForm()
        return render(request, 'photos/edit.html', {'form': form})


def index(request):
    photo_list = Photo.objects.all()
    ctx = {
        'photos': photo_list
    }
    return render(request, 'photos/index.html', ctx)


def hello(request):
    return HttpResponse("안녕하세요!")


def detail(request, pk, hidden=False):
    try:
        photo = Photo.objects.get(pk=pk)
    except Photo.DoesNotExist:
        return HttpResponse("사진이 없습니다.")

    if hidden is True:
        pass

    messages = (
        '<p>{pk}번 사진 보여줄게요</p>'.format(pk=photo.pk),
        '<img src={url}>'.format(url=photo.image.url),
        '<p>주소는 {url}</p>'.format(url=photo.image.url),
    )
    return HttpResponse('\n'.join(messages))


@login_required
def create(request):
    if request.method == "GET":
        form = PhotoForm()
    elif request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj = form.save()
            return redirect(obj)

    ctx = {
        'form': form,
    }

    return render(request, 'edit.html', ctx)

profiles/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.shortcuts import render


def profile(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    ctx = {
        'user': user,
    }

    return render(request, 'profile.html', ctx)

youstagram/views.py
from django.shortcuts import render

from photos.models import Photo


def index(request):
    photo_list = Photo.objects.all().order_by('-created_at')
    ctx = {
        'photo_list': photo_list
    }
    return render(request, 'index.html', ctx)

photos/templates/login.html
{% extends "layout.html" %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

{% if form.errors %}
  <p>ID나 비밀번호가 일치하지 않습니다.</p>
{% endif %}

<form method="POST" action="{% url 'login' %}">
  <input type="hidden" name="next" value="{{ next }}" />
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">로그인</button>
</form>

{% endblock %}

profiles/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
<h1>님의 프로필 페이지</h1>

<ul>
  {% for photo in user.photo_set.all %}
    <li><img src="" /></li>
  {% empty %}
    <li>게시한 사진이 없습니다.</li>
  {% endfor %}
</ul>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/spoqa.css' %}">

    <title>{% block page_title %}Index{% endblock %}</title>

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/" style="color:white">Pystagram</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

          <div class="navbar-form navbar-right">

            <a href="{% url 'blog:index' %}">
              <button class="btn btn-primary">Blog</button>
            </a>

            <a href="{% url 'photos:index' %}">
              <button class="btn btn-primary">Photos</button>
            </a>

            <a href="{% url 'counter:index' %}">
              <button class="btn btn-primary">Counter</button>
            </a>

            {% if user.is_authenticated %}
            {% else %}
              <a href="{% url "social:begin" "facebook" %}">
                <button class="btn btn-primary">페이스북으로 10초 만에 로그인</button>
              </a>
            {% endif %}

          </div>

        </div><!--/.navbar-collapse -->

      </div>
    </nav>

    <div class="container">
      <div class="col-md-12">
        {% block content %}{% endblock %}
      </div>
    </div>

    <hr />

    <footer>
      <p>&copy; CodeSquad</p>
    </footer>

  </body>

</html>

templates/blog/base.html
{% load staticfiles %}
<html>
  <head>
    <title>Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  </head>
  <body>
    <div class="page-header">
      <a href="{% url 'blog:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
      <h1><a href="{% url 'blog:index' %}">Blog</a></h1>
    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="post">
    {% if post.published_date %}
    <div class="date">
      {{ post.published_date }}
    </div>
    {% endif %}
    <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <h1>{{ post.title }}</h1>
    <p>{{ post.text|linebreaksbr }}</p>
  </div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>New post</h1>
<form method="POST" class="post-form">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in posts %}
    <div class="post">
      <div class="date">
        {{ post.published_date }}
      </div>
      <h1>
        <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
      </h1>
      <p>{{ post.text|linebreaksbr }}</p>
    </div>
  {% endfor %}
{% endblock content %}

templates/counter/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/asset/js/jquery-3.1.1.min.js"></script>

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="/asset/css/spoqa.css">


    <title>React App</title>
    <link href="/asset/counter/css/main.9a0fe4f1.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/" style="color:white">Pystagram</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

          <form class="navbar-form navbar-right">

            <a href="{% url 'blog:index' %}">
              <button class="btn btn-primary">Blog</button>
            </a>

            <a href="{% url 'photos:index' %}">
              <button class="btn btn-primary">Photos</button>
            </a>

            <a href="{% url 'counter:index' %}">
              <button class="btn btn-primary">Counter</button>
            </a>

            {% if user.is_authenticated %}
            {% else %}
              <a href="{% url "social:begin" "facebook" %}">
                <button class="btn btn-primary">페이스북으로 10초 만에 로그인</button>
              </a>
            {% endif %}

          </form>

        </div><!--/.navbar-collapse -->

      </div>
    </nav>

    <div class="col-md-12" id="root"></div>
    <script type="text/javascript" src="/asset/counter/js/main.c645e0eb.js"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1>Youstagram</h1>
    <p>인스타그램 관련 프로젝트</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="/" role="button">Learn more &raquo;</a></p> -->
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Blog</h2>
        <p>DjangoGirls Tutorial</p>
        <p><a class="btn btn-default" href="{% url 'blog:index' %}" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Photos</h2>
        <p>인스타그램</p>
        <p><a class="btn btn-default" href="{% url 'photos:index' %}" role="button">View details &raquo;</a></p>
     </div>
      <div class="col-md-4">
        <h2>Text-Counter</h2>
        <p>리액트로 구현한 글자수 세기</p>
        <p><a class="btn btn-default" href="{% url 'counter:index' %}" role="button">View details &raquo;</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/photos/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/spoqa.css' %}">

    <title>{% block page_title %}Index{% endblock %}</title>

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/" style="color:white">Pystagram</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

          <form class="navbar-form navbar-right">

            <a href="#">
              <button class="btn btn-primary">Blog</button>
            </a>
            <a href="#">
              <button class="btn btn-primary">Photos</button>
            </a>
            <a href="#">
              <button class="btn btn-primary">Lotto</button>
            </a>

            <a href="{% url "social:begin" "facebook" %}">
              <button class="btn btn-primary">페이스북으로 10초 만에 로그인</button>
            </a>

          </form>

        </div><!--/.navbar-collapse -->

      </div>
    </nav>

    <div class="container">
      <div class="col-md-12">
      {% block content %}{% endblock %}
      </div>
    </div>

    <hr />

    <footer>
      <p>&copy; CodeSquad</p>
    </footer>

  </body>

</html>

templates/photos/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

{% csrf_token %}
{{ form.as_p }}

<p><button type="submit">저장</button></p>
</form>

{% endblock %}

templates/photos/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-12">
  {% for photo in photos %}
    <div>
      <img src='{{ photo.image.url }}'>
      {{ photo.content }}
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/photos/login.html
{% extends 'base.html' %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

{% if form.errors %}
  <p>ID나 비밀번호가 일치하지 않습니다.</p>
{% endif %}

<form method="POST" action="{% url 'login' %}">
  <input type="hidden" name="next" value="{{ next }}" />
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">로그인</button>
</form>

{% endblock %}